# 4.1 The maximum-subarray problem

In [3]:
prices = [100,113,110,85,105,102,86,63,81,101,94,106,101,79,94,90,97]
changes = [13,-3,-25,20,-3,-16,-23,18,20,-7,12,-5,-22,15,-4,7]

In [147]:
def find_max_crossing_subarray(A, low, mid, high):
    left_cross_sum = -float('inf')
    total_sum = 0
    
    for i in range(mid,low-1,-1):
        total_sum = total_sum + A[i]
        if total_sum > left_cross_sum:
            left_cross_sum = total_sum
            max_left = i
    
    right_cross_sum = -float('inf')
    total_sum = 0    
    for j in range(mid+1, high+1):
        total_sum = total_sum + A[j]
        if total_sum > right_cross_sum:
            right_cross_sum = total_sum
            max_right = j
    
    return max_left, max_right, left_cross_sum+right_cross_sum

def find_maximum_subarray(A, low, high):
    
    if high == low:
        return low, high, A[low]
    
    else:
        mid = (low+high)//2
        left_low, left_high, left_sum = find_maximum_subarray(A, low, mid)
        right_low, right_high, right_sum = find_maximum_subarray(A, mid+1, high)
        cross_low, cross_high, cross_sum = find_max_crossing_subarray(A, low, mid, high)
        
        if left_sum >= right_sum and left_sum >= cross_sum:
            return left_low, left_high, left_sum
        
        elif right_sum >= left_sum and right_sum >= cross_sum:
            return right_low, right_high, right_sum
        
        else:
            return cross_low, cross_high, cross_sum

In [148]:
find_maximum_subarray(changes, 0, len(changes)-1)

(7, 10, 43)

## Exercises

### 4.1-1

The maximum subaray alghoritm will return the maximum out of those negative numbers.

In [149]:
negatives = [-3,-6,-6,-1,-8,-9]

In [150]:
find_maximum_subarray(negatives, 0, len(negatives)-1)

(3, 3, -1)

### 4.1-2

In [168]:
def find_maximum_subarray_brutoforce(A):
    iterations = 0
    total_profit = 0
    for i in range(len(A)):
#         print('Starting with {}'.format(i))
        for j in range(i+1,len(A)):
#             print('Combine {} with {}'.format(i,j))
            new_profit = A[j] - A[i]
            if new_profit > total_profit:
                total_profit = new_profit
                max_left = i
                max_right = j
            iterations += 1
    return max_left, max_right, total_profit, iterations

In [169]:
find_maximum_subarray_brutoforce(prices)

(7, 11, 43, 136)

In [171]:
find_maximum_subarray(changes, 0, len(changes)-1)

(7, 10, 43)

### 4.1-3

In [259]:
start = time.time()
find_maximum_subarray_brutoforce(prices+prices[:-5])
end = time.time()
diff_time = end - start


In [260]:
start = time.time()
find_maximum_subarray(changes+changes[:-3], 0, len(changes)-1)
end_2 = time.time()
diff_time_dc = end_2 - start


In [261]:
diff_time_dc - diff_time

0.000225067138671875

In [262]:
len(changes+changes[:-3])

29

In [2]:
len(prices+prices[:-5])

NameError: name 'prices' is not defined

On my computer the $n_0$ is 29. At this problem size onwards the devide and conquer algorithm performs btter

### 4.1-4

I do not understand this problem. Even tough I saw some solutions for this chapter, they are checking if there is at least one positive number. They do not mention anything about empty subarrays.

### 4.1-5

In [4]:
def find_maximum_subarray_linear(A):
    M = -float('inf')
    low_m = None
    M_r = 0
    low_r = 1
    for i in range(len(A)):
        M_r += A[i]
        if M_r > M:
            low_m = low_r
            high_m = i
            M = M_r
        elif M_r < 0:
            M_r = 0
            low_r = i+1
    return low_m, high_m, M

In [5]:
find_maximum_subarray_linear(changes)

(7, 10, 43)

# 4.2 Strassen's algorithm for matrix multiplication

In [1]:
import numpy as np

In [8]:
np.empty(shape = (3,3))

array([[1.94573012e-316, 6.92652346e-310, 6.92652346e-310],
       [6.92652346e-310, 6.92652346e-310, 6.92652346e-310],
       [6.92652346e-310, 6.92652346e-310, 6.92652346e-310]])

In [30]:
def square_matrix_multiply(A,B):
    import numpy as np
    
    n = A.shape[0]
    C = np.empty((n,n))
    for i in range(n):
        for j in range(n):
            C[i,j] = 0
            for k in range(n):
                C[i,j] = C[i,j] + A[i,k]*B[k,j]
    return C

In [18]:
A = np.asarray([0,1,2,3])
A = A.reshape((2,2))
B = np.asarray([4,5,6,7])
B = B.reshape((2,2))

In [137]:
print(A)
print(B)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [19]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [139]:
C = square_matrix_multiply(A,B)

In [140]:
C

array([[ 6.,  7.],
       [26., 31.]])

In [41]:
def square_matrix_multiply_recursive(A,B):
    n = len(A)
    C = np.empty((n,n))
    if n == 1:
        print('Write first element')
        C[0,0] = A * B
    else:
        C[0,0] = square_matrix_multiply_recursive(A[0,0],B[0,0]) + square_matrix_multiply_recursive(A[0,1], B[1,0])  
        
        C[0,1] = square_matrix_multiply_recursive(A[0,0],B[0,1]) + square_matrix_multiply_recursive(A[0,1], B[1,1])
            
        C[1,0] = square_matrix_multiply_recursive(A[1,0],B[0,0]) + square_matrix_multiply_recursive(A[1,1], B[1,0])
            
        C[1,1] = square_matrix_multiply_recursive(A[1,0],B[0,1]) + square_matrix_multiply_recursive(A[1,1], B[1,1])
    return C

In [42]:
square_matrix_multiply_recursive(A,B)

TypeError: object of type 'numpy.int64' has no len()

In [34]:
int(square_matrix_multiply_recursive(A[0,1],B[1,0]))

6

In [29]:
B[0,0]

4

In [16]:
(np.asarray([1])).shape[0]

1

## Excercises

### 4.2-1

In [3]:
A = np.asarray([1,3,7,5])
A = A.reshape((2,2))
B = np.asarray([6,8,4,2])
B = B.reshape((2,2))

In [5]:
A @ B

array([[18, 14],
       [62, 66]])

In [7]:
S1 = B[0,1] - B[1,1]
S2 = A[0,0] + A[0,1]
S3 = A[1,0] + A[1,1]
S4 = B[1,0] - B[0,0]
S5 = A[0,0] + A[1,1]
S6 = B[0,0] + B[1,1]
S7 = A[0,1] - A[1,1]
S8 = B[1,0] + B[1,1]
S9 = A[0,0] - A[1,0]
S10 = B[0,0] + B[0,1]

In [8]:
P1 = A[0,0] * S1
P2 = B[1,1] * S2
P3 = B[0,0] * S3
P4 = A[1,1] * S4
P5 = S5 * S6 
P6 = S7 * S8
P7 = S9 * S10

In [9]:
C = np.empty((2,2))

In [10]:
C[0,0] = P5+P4-P2+P6
C[0,1] = P1+P2
C[1,0] = P3+P4
C[1,1] = P5+P1-P3-P7

In [12]:
C == A@B

array([[ True,  True],
       [ True,  True]])

### 4.2-2

In [ ]:
def strassen(A,B):
    if A.size == 1 and B.size == 1:
        return A * B
    n = A.shape[0]
    C = np.empty((n,n))
    A