# 6.1 Heaps

In [1]:
def parent(i):
    import math
    return math.floor(i/2)

In [2]:
def left(i):
    return 2*i + 1 

In [3]:
def right(i):
    return 2*i + 2

# 6.2 Maintaining the heap property

In [4]:
def max_heapify(A,n,i):
    l = left(i)
    r = right(i)
    if l <= n-1 and A[l] > A[i]:
        largest = l
    else:
        largest = i
    if r <= n-1 and A[r] > A[largest]:
        largest = r
    if largest != i:
        A[i], A[largest] = A[largest], A[i]
        max_heapify(A,n,largest)
    return A

In [5]:
array = [16,4,10,14,7,9,3,2,8,1]

In [6]:
max_heapify(array,len(array),1)

[16, 14, 10, 8, 7, 9, 3, 2, 4, 1]

## 6.2-2

In [7]:
def min_heapify(A,n,i):
    l = left(i)
    r = right(i)
    if l <= n-1 and A[l] < A[i]:
        smallest = l
    else:
        smallest = i
    if r <= n-1 and A[r] < A[smallest]:
        smallest = r
    if smallest != i:
        A[i], A[smallest] = A[smallest], A[i]
        min_heapify(A,n,smallest)
    return A

In [8]:
array = [16,4,10,14,7,9,3,2,8,1]
min_heapify(array,len(array),3)

[16, 4, 10, 2, 7, 9, 3, 14, 8, 1]

## 6.2-5

In [9]:
def max_heapify_loop(A,i):
    while True:
        l = left(i)
        r = right(i)
        if l <= len(A) and A[l] > A[i]:
            largest = l
        else:
            largest = i
        if r <= len(A) and A[r] > A[largest]:
            largest = r
        if largest == i:
            return
        A[i], A[largest] = A[largest], A[i]
        i = largest
        return A

In [10]:
array = [16,4,10,14,7,9,3,2,8,1]
max_heapify_loop(array,1)

[16, 14, 10, 4, 7, 9, 3, 2, 8, 1]

# 6.3 Building a heap

In [11]:
def build_max_heap(A):
    import math
    n = len(A)
    for i in range(math.floor(n/2)-1,-1,-1):
        max_heapify(A,n,i)
    return A

In [12]:
def build_min_heap(A):
    import math
    n = len(A)
    for i in range(math.floor(n/2)-1,-1,-1):
        min_heapify(A,n,i)
    return A

## 6.3-1

In [13]:
array = [5,3,17,10,84,19,6,22,9]
build_max_heap(array)

[84, 22, 19, 10, 3, 17, 6, 5, 9]

## 6.3-2

If we start from the first element to $\lfloor\frac{n}{2}\rfloor$ there is not guarantee that the we will have max-heaps.

## 6.3-3

# 6.4 The heapsort algorithm

In [14]:
def heapsort(A):
    n = len(A)
    A = build_max_heap(A)
    for i in range(n-1,0,-1):
        A[0], A[i] = A[i], A[0]
        n -= 1
        max_heapify(A,n,0)
    return A

## 6.4-1

In [15]:
array = [5,13,2,25,7,17,20,8,4]

heapsort(array)

[2, 4, 5, 7, 8, 13, 17, 20, 25]

## 6.4-2

Before first iteration of the loop the whole array is a max-heap. In each consecutive iteration the array $A[1..i]$ is a max_heap and it contains i smallest elements because biggest elements are moved to the end of the array and their indeces are greater than $i$. And by the construction of the algorithm those elements are already sorted.

In [16]:
def heapsort_invariant(A):
    n = len(A)
    A = build_max_heap(A)
    for i in range(n-1,0,-1):
        print(f"Array before loop iteration {A}")
        A[0], A[i] = A[i], A[0]
        n -= 1
        max_heapify(A,n,0)
        print(f"Array after loop iteration {A}\n")
    return A

In [17]:
array = [5,13,2,25,7,17,20,8,4]

heapsort_invariant(array)

Array before loop iteration [25, 13, 20, 8, 7, 17, 2, 5, 4]
Array after loop iteration [20, 13, 17, 8, 7, 4, 2, 5, 25]

Array before loop iteration [20, 13, 17, 8, 7, 4, 2, 5, 25]
Array after loop iteration [17, 13, 5, 8, 7, 4, 2, 20, 25]

Array before loop iteration [17, 13, 5, 8, 7, 4, 2, 20, 25]
Array after loop iteration [13, 8, 5, 2, 7, 4, 17, 20, 25]

Array before loop iteration [13, 8, 5, 2, 7, 4, 17, 20, 25]
Array after loop iteration [8, 7, 5, 2, 4, 13, 17, 20, 25]

Array before loop iteration [8, 7, 5, 2, 4, 13, 17, 20, 25]
Array after loop iteration [7, 4, 5, 2, 8, 13, 17, 20, 25]

Array before loop iteration [7, 4, 5, 2, 8, 13, 17, 20, 25]
Array after loop iteration [5, 4, 2, 7, 8, 13, 17, 20, 25]

Array before loop iteration [5, 4, 2, 7, 8, 13, 17, 20, 25]
Array after loop iteration [4, 2, 5, 7, 8, 13, 17, 20, 25]

Array before loop iteration [4, 2, 5, 7, 8, 13, 17, 20, 25]
Array after loop iteration [2, 4, 5, 7, 8, 13, 17, 20, 25]



[2, 4, 5, 7, 8, 13, 17, 20, 25]

## 6.4-3

* Sorted array in increasing order:
    - The call on **build_max_heap** will take $\Theta(n\lg{n})$ time
    - The *for* loop has $n$ iterations and each call to **max_heapify** takes $\lg n$ time, so the overal running time of the *for* loop is $\Theta(n\lg{n})$
    - The whole **heapsort** algorithm will take  $\Theta(n\lg{n})$
* Sorted array in decreasing order:
    - The array is already a *max-heap* so **build_max_heap** will take only $\Theta(n)$ time as it will make n calls to **max_heapify**, which in this scenario will take only constant time.
    - However, the algorithm running time will be dominated by the *for* loop as it will still take $\Theta(n\lg{n})$


## 6.4-4

This problem is the same as one of the cases of **6.4-3**. The worst case scenario would be when the array is sorted in decreasing order. The worst-case running time of the algorithm will be $\Theta(n\lg{n})$

## 6-4.5

My logic for this problem is the same as in the case when the array is already sorted. But then I do not know how to use the information that the elements are distinct.

# 6.5 Priority queues

In [18]:
def heap_maximum(A):
    return A[0]

In [19]:
def heap_extract_max(A,n):
    if n < 1:
        raise ValueError('heap underflow')
    maximum = A[0]
    A[0] = A[n-1]
    n -= 1
    max_heapify(A,n,0)
    return maximum, A[:n]  

In [20]:
def heap_increase_key(A,i,key):
    if key < A[i-1]:
        raise ValueError('new key is smaller than current key')
    A[i] = key
    while i>0 and A[parent(i)] < A[i]:
        A[i], A[parent(i)] = A[parent(i)], A[i]
        i = parent(i)

In [21]:
def max_heap_insert(A,key):
    A.append(-float('inf'))
    n = len(A)
    heap_increase_key(A,n-1,key)
    return A

## 6.5-1

In [22]:
A = [15,13,9,5,12,8,7,4,0,6,2,1]
heap_extract_max(A,len(A))[1]

[13, 12, 9, 5, 6, 8, 7, 4, 0, 1, 2]

## 6.5-2

In [23]:
A = [15,13,9,5,12,8,7,4,0,6,2,1]
max_heap_insert(A,10)

[15, 13, 9, 10, 12, 8, 5, 4, 0, 6, 2, 1, 7]

## 6.5-3

In [24]:
def heap_minimum(A):
    return A[0]

In [25]:
def heap_extract_min(A,n):
    if n < 1:
        raise ValueError('heap underflow')
    minimum = A[0]
    A[0] = A[n-1]
    n -= 1
    min_heapify(A,n,0)
    return minimum, A[:n]  

In [26]:
def heap_decrease_key(A,i,key):
    if key < A[i-1]:
        raise ValueError('new key is smaller than current key')
    A[-1] = key
    n = len(A)
    build_min_heap(A)

In [27]:
def min_heap_insert(A,n,key):
    A.append(-float('inf'))
    n = len(A)
    heap_decrease_key(A,n,key)
    return A

## 6.5-4

We insert $-\infty$ in order to make sure that an error will not be raised. However, I do not understand why we just don't add the element at the end and skip several opearions - insert $-\infty$, compare it with the new key, replace those two.

## 6.5-5

At the beginning we have a heap structure and we replace the last ($i$th) element with the new key value. The only possible parent-child pair where the heap property my not held is between the $i$th element and its parent. This is true in the next iterations until the heap property is restored.

## 6.5-6

In my implementation I cannot replace anything.

## 6.5-7



## 6.5-8

In [28]:
def heap_delete(A,i):
    A[i] = float('inf')
    n = len(A)
    build_max_heap(A)
    A[0], A[-1] = A[-1], A[0]
    del A[-1]    
    build_max_heap(A)
    return A

In [29]:
A = [15,13,9,5,12,8,7,4,0,6,2,1]
heap_delete(A,4)

[15, 13, 9, 5, 6, 8, 7, 4, 0, 1, 2]

Unfortunately I cant think of a way to run this is $\lg n$ time. My implementation runs for $n\lg n$ because of **build_max_heap**

## 6.5-9

Take the first element in all of the $k$ sorted lists. Run **min_heapify** at the root. Then from the $k$ lists get the minimum element out of all $k$ first element. Append it in the heap array and run **min_heapify** in the position of its parent. Continue with this. We will run this $n$ times, but I am not sure if **min_heapify** will run for $lg k$ or $lg n$ time.

# Problems

## 6-1
### a.

In [30]:
def build_max_heap2(A):
    for i in range (1,len(A)):
        B = max_heap_insert(A[:i],A[i])
    return B

In [31]:
A = [1,2,3,4,5]
print(build_max_heap2(A))
print(build_max_heap(A))

[5, 1, 2, 4, 3]
[5, 4, 3, 1, 2]


### b.

Calling *max_heap_insert* takes $\Theta (\lg n)$ time. And we call it $n-1$ times. So, the overall running time of *build_max_heap2* is $\Theta (n\lg n)$

## 6-2
### a.

The root of the heap will be still at $A[1]$. The root children are located in elements from $A[2]$ to $A[d+1]$. The second generation of children are located in elements from $A[d+2]$ to $A[(d+1)^2]$.

We can get the parent of an element in a **d-ary heap** by replacing in the formula for *parent* $2$ with $d$

In [32]:
def parent_d(i,d):
    import math
    return math.floor(i/d)

In [33]:
def child_d(i,d,k):
    return d*i + k + 1

In [34]:
#check the function
parent_d(child_d(1,4,2),4)

1

### b.
Analogically to the binary heap, a d-ary heap's height would be $\log_dn = \frac{\lg n}{\lg d}$

### c.

The *heap_extract_max* would work for **d-ary heap** if we make a change in *max_heapify*. The necessary change is that instead of comparing with just two children in the case of a binary heap, we need to make the comparison with **d** children.

In [35]:
def heap_extract_max_d(A,n):
    if n < 1:
        raise ValueError('heap underflow')
    maximum = A[0]
    A[0] = A[n-1]
    n -= 1
    max_heapify_d(A,n,0)
    return maximum, A[:n]  

In [36]:
def max_heapify_d(A,n,i,d):
    largest = i
    for j in range(1,d+1):
        if child_d(i,d,j)<= n-1 and A[child_d(i,d,j)] > A[i] and A[child_d(i,d,j)] > A[i] > largest:
            largest = A[d-ARY-CHILD(k, i)]
    if largest != i:
        A[i], A[largest] = A[largest], A[i]
        max_heapify_d(A,n,largest,d)
    return A

The complexity of *heap_extract_max_d*, as well as in the case of the binary heap, is connected to *max_heapify_d* procedure. It depends on how many children each element has ($d$) and the height of the heap ($\log_dn$). The running time of *heap_extract_max_d* is $\Theta(d\log_dn)$.

### d.
For this task, we need to change a bit the function *heap_increase_key*. More specifically, the part which calculates the parent. Apart from that, the original *heap_increase_key* functions should work. The running time is $\Theta(\log_dn)$ - comes from the height of the **d-ary** heap which sets the running time of *heap_increase_key_d*.

In [37]:
def heap_increase_key_d(A,i,key,d):
    if key < A[i-1]:
        raise ValueError('new key is smaller than current key')
    A[i] = key
    while i>0 and A[parent_d(i,d)] < A[i]:
        A[i], A[parent_d(i,d)] = A[parent_d(i,d)], A[i]
        i = parent_d(i,d)

In [38]:
def max_heap_insert_d(A,key,d):
    A.append(-float('inf'))
    n = len(A)
    heap_increase_key_d(A,n-1,key,d)
    return A

### e.
The solution to this problem is shown in the previous section.

## 6-3
### a.

In [39]:
import numpy as np
Y = np.array([(2,3,4), (5,8,9), (12,14,16)],dtype=np.float)
Y

array([[ 2.,  3.,  4.],
       [ 5.,  8.,  9.],
       [12., 14., 16.]])

### b.
Following the definition of **Young tableau**, if the first element, $Y[1,1]$ is $\infty$, then this would mean that the smallest element is $\infty$. Therefore, all other elements must be at least $\infty$. This would mean that $Y$ is empty. Analogically, we can conlcude that $Y$ is full if the last element, $Y[m,n]<\infty$

### c.

In [40]:
#not working
def extract_min_yt(Y,i,j):
    minimum = Y[i,j]
    Y[i,j] = float('inf')
    if i >= Y.shape[0]-1 or j >= Y.shape[1]-1:
        return minimum
    if Y[i,j+1] == Y[i+1,j] == float('inf'):
        Y[i,j] = float('inf')
        return minimum
    if Y[i,j+1] < Y[i+1,j]:
        Y[i,j] = Y[i,j+1]
        Y[i,j+1]=minimum
        return extract_min_yt(Y,i,j+1)
    else:
        Y[i,j] = Y[i+1,j]
        Y[i+1,j]=minimum
        return extract_min_yt(Y,i+1,j)

In [41]:
extract_min_yt(Y,0,0)

2.0

In [42]:
Y

array([[ 3.,  4., inf],
       [ 5.,  8.,  9.],
       [12., 14., 16.]])

### d.

In [43]:
#not working

def insert_yt(Y,key):
    i = Y.shape[0]-1
    j = Y.shape[1]-1
    Y[i, j] = key
    while Y[i-1, j] > Y[i, j] or Y[i, j-1] > Y[i, j]:
        if Y[i-1, j] < Y[i, j-1]:
            Y[i, j], Y[i, j-1] = Y[i, j-1], Y[i, j]
            j-=1
        else:
            Y[i, j], Y[i-1, j] = Y[i-1, j], Y[i, j]
            i-=1

In [44]:
Y = np.array([(2,3,4), (5,8,9), (12,14,16)],dtype=np.float)

insert_yt(Y,1)

IndexError: index -4 is out of bounds for axis 1 with size 3

### e.
Starting from an empty **Young Tableau** we will be using the function *insert_yt* for each element for a total of $n^2$ times. Then do the actual sorting by calling the function *extract_min_yt* $n^2$ times and then store the new sorted array. 

### f.

In [45]:
def search_yt(Y,key):
    i=j= 0
    while i< Y.shape[0] and Y[i,j] <= key:
        if Y[i, j] == key:
            return True
        i+=1
    i-=1
    while j < Y.shape[1] and (i >= 0 and i < Y.shape[0]):
        if Y[i, j] == key:
            return True
        if Y[i, j] < key:
            j+=1
        else:
            i-=1
    return False
            
        

In [46]:
Y = np.array([(2,3,4), (5,8,9), (12,14,16)],dtype=np.float)
Y

array([[ 2.,  3.,  4.],
       [ 5.,  8.,  9.],
       [12., 14., 16.]])

In [47]:
search_yt(Y,15)

False

In [48]:
search_yt(Y,8)

True